version: '2'
services:
  web-pozzos:
    image: php:apache
    depends_on:
      - api-pozzos
    ports:
      - "8082:80"
    volumes:
      - ./website:/var/www/html
    environment:
      - USERNAME=toto
      - PASSWORD=python
    networks:
      - api_pozzos
  api-pozzos:
    image: app-pozzos:v1
    ports:
      - "4000:5000"
    volumes:
      - ./simple_api/student_age.json:/data/student_age.json
    networks:
      - api_pozzos

networks:
  api_pozzos:

